---
version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - 8083:80
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  wordpressnet:
    ipam:
      driver: default
      config:
        - subnet: 10.50.1.0/24