version: "3"
services:
  website:
    image: nginx
    ports:
      - "8081:80"
    restart: always

  website2:
    image: nginx
    ports:
      - "8082:80"
    restart: always
    networks:
      bleoweb:
        ipv4_address: 160.20.0.21
networks:
  bleoweb:
    ipam:
      driver: default
      config:
        - subnet: "160.20.0.1/24"